# Generated by Django 6.0.1 on 2026-01-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the ad configuration', max_length=100)),
                ('ad_type', models.CharField(choices=[('HOME_FEED', 'Home Feed'), ('DRAMA_PLAYER', 'Drama Player')], max_length=20)),
                ('code', models.TextField(help_text='The HTML/Script code for the ad')),
                ('sequence', models.IntegerField(default=1, help_text='Frequency of the ad. E.g., 2 means every 2nd item/episode.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
