# Generated by Django 6.0.1 on 2026-01-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adconfig',
            name='random_max',
            field=models.IntegerField(default=5, help_text='Maximum interval for random sequence (e.g., 5)'),
        ),
        migrations.AddField(
            model_name='adconfig',
            name='random_min',
            field=models.IntegerField(default=2, help_text='Minimum interval for random sequence (e.g., 2)'),
        ),
        migrations.AddField(
            model_name='adconfig',
            name='show_random',
            field=models.BooleanField(default=False, help_text='If enabled, uses random interval between random_min and random_max instead of fixed sequence'),
        ),
        migrations.AlterField(
            model_name='adconfig',
            name='sequence',
            field=models.IntegerField(default=1, help_text='Frequency of the ad. E.g., 2 means every 2nd item/episode. (Ignored if show_random is True)'),
        ),
    ]
