# Generated by Django 6.0.1 on 2026-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoliboxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Config identifier (e.g., 'Production', 'Test')", max_length=100)),
                ('joli_source_token', models.TextField(help_text='Jolibox API source token')),
                ('device_id', models.CharField(help_text='Device identifier', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only active config will be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jolibox Configuration',
                'verbose_name_plural': 'Jolibox Configurations',
            },
        ),
    ]
