# Generated by Django 6.0.1 on 2026-01-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joliboxconfig',
            options={'verbose_name': 'Jolibox Configuration', 'verbose_name_plural': 'Jolibox Configuration'},
        ),
        migrations.RemoveField(
            model_name='joliboxconfig',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='joliboxconfig',
            name='device_id',
            field=models.CharField(blank=True, default='', help_text='Device identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='joliboxconfig',
            name='joli_source_token',
            field=models.TextField(blank=True, default='', help_text='Jolibox API source token'),
        ),
        migrations.AlterField(
            model_name='joliboxconfig',
            name='name',
            field=models.CharField(default='Default', help_text='Config identifier', max_length=100),
        ),
    ]
