# Generated by Django 6.0.1 on 2026-01-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0002_remove_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joliboxconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='joliboxconfig',
            name='name',
        ),
        migrations.RemoveField(
            model_name='joliboxconfig',
            name='updated_at',
        ),
    ]
