# Generated by Django 6.0.1 on 2026-01-19 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramas', '0003_simplify_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drama_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_url', models.URLField(blank=True, default='', max_length=2000)),
                ('logo_url', models.URLField(blank=True, default='', max_length=2000)),
                ('episode_count', models.IntegerField(default=0)),
                ('orientation', models.CharField(default='VERTICAL', max_length=20)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('views', models.IntegerField(default=0)),
                ('status', models.CharField(default='PUBLISHED', max_length=50)),
                ('host_mode', models.CharField(default='JOLIBOX_HOST', max_length=50)),
                ('content_provider_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drama',
                'verbose_name_plural': 'Dramas',
                'ordering': ['-views', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('drama', 'Single Drama'), ('episodes', 'Episodes Only')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('dramas_synced', models.IntegerField(default=0)),
                ('episodes_synced', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('video_url', models.URLField(blank=True, default='', max_length=2000)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlock_error', models.TextField(blank=True, default='')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='dramas.drama')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['drama', 'episode_number'],
                'unique_together': {('drama', 'episode_number')},
            },
        ),
    ]
